name: Build Project

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    types: [opened, reopened, edited]
  workflow_dispatch:

jobs:  
  verify:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set Up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'zulu'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Compile Gradle Project
      run: ./gradlew clean dist
